WEBSOCKET_URL = ""   # add real feed URL later
TICKER_API = ""      # add ticker API
TICKER_API_KEY = ""

KALSHI_ENABLED = False
KALSHI_API_KEY = ""
KALSHI_DEMO = True

PROBABILITY_THRESHOLD = 0.50
TRADE_SIZE = 20

MIN_GOAL_MINUTE = 0
MAX_GOAL_MINUTE = 120
